### ISSUE TITLE
Initial Users

### ISSUE THREAD

**Issue by dmaynor** [hiattp/express3-mongodb-bootstrap-demo#3]
What is the best way to load a set of initial users if you didn't want to go through register for each one?

Because of crypt and salt I can't just insert them into the DB, I could pregenerate all the passwords but I was hoping to do password auditing and have a predetermined list of passwords isn't good for testing.

**Comment by hiattp** [comment]
So if you are generating the users yourself, wouldn't the password have to be predetermined somehow regardless of encryption? I suppose you could randomly generate them. Either way, you can just write a script that creates a bunch of new User objects with fake data and use the normal `save`. That will encrypt the passwords, but since all other users will have encrypted passwords I'd think that's what you want.

Are you trying to test password validations, or what is the use-case you are trying to accomplish?

**Comment by dmaynor** [comment]
I just wrote a script and incudled mongoose and the schema/models and scripted the adds.

I created 10k accounts with weak dictionary passwords, 10k with ok passwords and 10k with strong passwords. For the next 7 days I am running brute force tools against the three instances (on for each password security level) and get results on the effectiveness of brute forcing vs password length. It seems like a no brainer but there isn't a lot of good data to cite in a paper.

Thank you for your help!
